name: "dehydrated"
description: "get certificates via dehydrated.sh"
version: "1.0.0"
slug: "dehydrated"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl:rw
image: "ghcr.io/zifnab06/dehydrated-{arch}"
